[platformio]
default_envs = esp32-d1mini

[env:esp32-d1mini]
platform = espressif32 @ ^6.5.0
board = wemos_d1_mini32
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv

lib_deps =
  SignalK/SensESP @ ^3.2.0
  adafruit/Adafruit SH110X @ ^2.1.10
  adafruit/Adafruit GFX Library @ ^1.11.9
  bblanchon/ArduinoJson @ ^7.0.0

build_flags =
  -std=gnu++17
  -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
  -D TAG='"ARDUINO"'
  -D USE_ESP_IDF_LOG

lib_compat_mode = strict
lib_ldf_mode = chain
